### ISSUE TITLE
Popup menus collapse to  zero height on firefox until browser window is resized

### ISSUE THREAD

**Issue by arkanoid87** [grocy/grocy-docker#239] opened 2024-03-09 17:40 UTC
Tested on Firefox 122.0.1 on Windows and Linux 

![image](https://github.com/grocy/grocy-docker/assets/1446586/05ac4541-7f89-4794-8efd-527c6221d476)

resizing browser window (any distance is good) redraws the popup with correct height

**Comment by berrnd** [comment] 2024-03-09 17:50
Duplicate of #237 and a lot more there referenced ones - please check existing requests before opening new ones.

Also note that this is mostly already fixed in [Grocy v4.1.0](https://grocy.info/changelog#v4.1.0), but grocy-docker is currently unmaintained (see README and the pinned issue) and therefore uses (the outdated) Grocy v4.0.3 release now and as long as someone takes this project over.

**Closed by berrnd** 2024-03-09 17:50 UTC
Labels: duplicate

**Comment by berrnd** [comment] 2024-03-09 18:14
> I suggest to write it clearly into the readme, before the title, larger, bigger

From my multiple year experience with (not only) this project, the people who don't read README's, don't read README's, regardless of the font size choosen. But feel more than free to do that, I'm not maintaining grocy-docker.
