### ISSUE TITLE
Question: what are the `read_only: true` for in docker-compose.yml 

### ISSUE THREAD

**Issue by tet3** [grocy/grocy-docker#66] opened 2020-04-02 00:16 UTC
They appear at the service level for both `grocy` and `grocy-nginx`.  Per the [docs for v2 of docker-compose YAML](https://docs.docker.com/compose/compose-file/compose-file-v2/#volumes), `read_only:true` is only supposed to be a field within a `volume` definition. The file validates, and seems to work (mostly - posting another issue in a second), but it doesn't make sense to me that **all** the volumes in each container would be read-only, and the short-form definition for `grocy-nginx`'s access to `www-public` is marked with the `:ro` suffix. So it seems like at best that line isn't doing anything, and at worst preventing write to one or more volumes that clearly need writing to. But I'm a grocy and docker noob, and could definitely be wrong here.

**Comment by jayaddison** [comment] 2020-04-02 00:50
@tet3 Good question; those lines mark the container image filesystem (visible as the 'root filesystem' for processes inside the container) as read-only -- as it sounds like you may have already discovered :)

The `tmpfs` mount points and the `volumes` defined on each service are read-write by default (except when explicitly imported with the `ro` flag you mentioned).

Although I couldn't find great references in the Docker Compose File documentation, this article could be relevant to explain why this can be useful:

https://www.projectatomic.io/blog/2015/12/making-docker-images-write-only-in-production/

I'll leave this issue open for now since it sounds like there could be further conversation.

**Comment by BlueBlueBlob** [comment] 2020-04-02 10:51
Hi
I can tell it changes something about building nginx.

[ro_true.txt](https://github.com/grocy/grocy-docker/files/4420498/ro_true.txt)
[ro_false.txt](https://github.com/grocy/grocy-docker/files/4420499/ro_false.txt)

Not sure if it's really related to the flag... Sorry
Tell me if I need to open an issue.

Regards

**Comment by jayaddison** [comment] 2020-04-02 15:12
@BlueBlueBlob I'll need a little more information to be completely sure, but my guess is that your `ro_true.txt` ran against the code merged in https://github.com/grocy/grocy-docker/pull/58 (merged into master @ fb96061).  This contained a directory permissions bug.

I believe that was fixed by https://github.com/grocy/grocy-docker/pull/59 (merged into master @ 0b48518).

**Comment by jayaddison** [comment] 2020-04-02 15:16
@BlueBlueBlob If you'd like to confirm the cause of the build failure, please provide a hyperlink to the full Travis build.

The failing log line is:
```
nginx: [emerg] mkdir() "/var/lib/nginx/tmp/client_body" failed (30: Read-only file system)
```

**Comment by jayaddison** [comment] 2020-04-02 15:17
@tet3 Hopefully we're good here in terms of discussion regarding the `read_only` flag.  Feel free to re-open the issue if you'd like to know more.

**Comment by BlueBlueBlob** [comment] 2020-04-02 15:32
Sorry i miss some comments.
But I will try with your last commits 👍

**Comment by jayaddison** [comment] 2020-04-02 16:28
Hmm.. having done some more reading, it looks like we may want to make the `www-public` volume `ro` even inside the PHP container.  Certainly we shouldn't be modifying the contents of this directory after vendor dependencies are written to it.  The two-container setup makes this situation a little more complicated, but still manageable, I think.

**Comment by jayaddison** [comment] 2020-04-02 16:32
@BlueBlueBlob Thanks; please be aware that running builds against the `master` branch of `grocy-docker` can be a little risky since this includes work-in-progress and unreleased changes.

A new release of `grocy-docker` should be arriving soon (within the next few days).

**Comment by jayaddison** [comment] 2020-04-02 17:02
Closing this issue; progress against a new release of `grocy-docker` will be tracked in https://github.com/grocy/grocy-docker/issues/41

Pull request #71 introduced further usage of the `ro` volume flag, and discusses future options for improvement.

**Closed by jayaddison** 2020-04-02 17:02 UTC
