### ISSUE TITLE
Quickstart guid do not work

### ISSUE THREAD

**Issue by Mannshoch** [grocy/grocy-docker#131] opened 2021-05-30 09:23 UTC
I'm trying to follow the Quickguide to setup my Raspi but it seems not working:

docker pull grocy/nginx
docker pull grocy/grocy
both not working. Latest seems not existing. needed to request by tag. -> docker pull grocy/grocy:v3.0.1-11

after that I do not know how to work with this step:
```
docker-compose pull
docker-compose up
```
It seems that the Quickstart is not complete. I'm not an Expert with docker, please update the Quickguide.

**Comment by Mannshoch** [comment] 2021-06-03 11:56
From Subreddit I followed the proposal to use https://hub.docker.com/r/linuxserver/grocy
That worked without problems.

I would propose to replace the README content with a link to https://hub.docker.com/r/linuxserver/grocy

**Comment by jayaddison** [comment] 2021-06-04 22:48
Thanks @Mannshoch; this is true, the default instructions here appear not to work since there is no `latest` tag on the published `grocy/grocy` and `grocy/nginx` Docker Hub images.

At the moment my time maintaining this project is limited; sorry for that.  If you have time for a pull request or suggestion, that would be welcome.

Closing as a duplicate of #129.

**Closed by jayaddison** 2021-06-04 22:48 UTC
